//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaquetePuntoControl
    {
        public Nullable<int> idPaquete { get; set; }
        public Nullable<int> idPuntoControl { get; set; }
        public Nullable<System.DateTime> fechaLlegada { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<bool> borrado { get; set; }
        public Nullable<int> retraso { get; set; }
        public int id { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual PuntoControl PuntoControl { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
