//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuntoControl()
        {
            this.PaquetePuntoControl = new HashSet<PaquetePuntoControl>();
        }
    
        public Nullable<int> idTrayecto { get; set; }
        public Nullable<int> idAgencia { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> tiempo { get; set; }
        public int id { get; set; }
        public Nullable<bool> borrado { get; set; }
        public string nombre { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaquetePuntoControl> PaquetePuntoControl { get; set; }
        public virtual Trayecto Trayecto { get; set; }
    }
}
